// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: vault_v1.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PasswordManagerAccess.ProtonPass.Protobuf {

  /// <summary>Holder for reflection information generated from vault_v1.proto</summary>
  public static partial class VaultV1Reflection {

    #region Descriptor
    /// <summary>File descriptor for vault_v1.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VaultV1Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg52YXVsdF92MS5wcm90bxIUcHJvdG9uX3Bhc3NfdmF1bHRfdjEieQoXVmF1",
            "bHREaXNwbGF5UHJlZmVyZW5jZXMSLQoEaWNvbhgBIAEoDjIfLnByb3Rvbl9w",
            "YXNzX3ZhdWx0X3YxLlZhdWx0SWNvbhIvCgVjb2xvchgCIAEoDjIgLnByb3Rv",
            "bl9wYXNzX3ZhdWx0X3YxLlZhdWx0Q29sb3IiagoFVmF1bHQSDAoEbmFtZRgB",
            "IAEoCRITCgtkZXNjcmlwdGlvbhgCIAEoCRI+CgdkaXNwbGF5GAMgASgLMi0u",
            "cHJvdG9uX3Bhc3NfdmF1bHRfdjEuVmF1bHREaXNwbGF5UHJlZmVyZW5jZXMq",
            "kQMKCVZhdWx0SWNvbhIUChBJQ09OX1VOU1BFQ0lGSUVEEAASDwoLSUNPTl9D",
            "VVNUT00QARIJCgVJQ09OMRACEgkKBUlDT04yEAMSCQoFSUNPTjMQBBIJCgVJ",
            "Q09ONBAFEgkKBUlDT041EAYSCQoFSUNPTjYQBxIJCgVJQ09ONxAIEgkKBUlD",
            "T044EAkSCQoFSUNPTjkQChIKCgZJQ09OMTAQCxIKCgZJQ09OMTEQDBIKCgZJ",
            "Q09OMTIQDRIKCgZJQ09OMTMQDhIKCgZJQ09OMTQQDxIKCgZJQ09OMTUQEBIK",
            "CgZJQ09OMTYQERIKCgZJQ09OMTcQEhIKCgZJQ09OMTgQExIKCgZJQ09OMTkQ",
            "FBIKCgZJQ09OMjAQFRIKCgZJQ09OMjEQFhIKCgZJQ09OMjIQFxIKCgZJQ09O",
            "MjMQGBIKCgZJQ09OMjQQGRIKCgZJQ09OMjUQGhIKCgZJQ09OMjYQGxIKCgZJ",
            "Q09OMjcQHBIKCgZJQ09OMjgQHRIKCgZJQ09OMjkQHhIKCgZJQ09OMzAQHyqu",
            "AQoKVmF1bHRDb2xvchIVChFDT0xPUl9VTlNQRUNJRklFRBAAEhAKDENPTE9S",
            "X0NVU1RPTRABEgoKBkNPTE9SMRACEgoKBkNPTE9SMhADEgoKBkNPTE9SMxAE",
            "EgoKBkNPTE9SNBAFEgoKBkNPTE9SNRAGEgoKBkNPTE9SNhAHEgoKBkNPTE9S",
            "NxAIEgoKBkNPTE9SOBAJEgoKBkNPTE9SORAKEgsKB0NPTE9SMTAQC0IsqgIp",
            "UGFzc3dvcmRNYW5hZ2VyQWNjZXNzLlByb3RvblBhc3MuUHJvdG9idWZiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PasswordManagerAccess.ProtonPass.Protobuf.VaultIcon), typeof(global::PasswordManagerAccess.ProtonPass.Protobuf.VaultColor), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PasswordManagerAccess.ProtonPass.Protobuf.VaultDisplayPreferences), global::PasswordManagerAccess.ProtonPass.Protobuf.VaultDisplayPreferences.Parser, new[]{ "Icon", "Color" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PasswordManagerAccess.ProtonPass.Protobuf.Vault), global::PasswordManagerAccess.ProtonPass.Protobuf.Vault.Parser, new[]{ "Name", "Description", "Display" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum VaultIcon {
    [pbr::OriginalName("ICON_UNSPECIFIED")] IconUnspecified = 0,
    [pbr::OriginalName("ICON_CUSTOM")] IconCustom = 1,
    [pbr::OriginalName("ICON1")] Icon1 = 2,
    [pbr::OriginalName("ICON2")] Icon2 = 3,
    [pbr::OriginalName("ICON3")] Icon3 = 4,
    [pbr::OriginalName("ICON4")] Icon4 = 5,
    [pbr::OriginalName("ICON5")] Icon5 = 6,
    [pbr::OriginalName("ICON6")] Icon6 = 7,
    [pbr::OriginalName("ICON7")] Icon7 = 8,
    [pbr::OriginalName("ICON8")] Icon8 = 9,
    [pbr::OriginalName("ICON9")] Icon9 = 10,
    [pbr::OriginalName("ICON10")] Icon10 = 11,
    [pbr::OriginalName("ICON11")] Icon11 = 12,
    [pbr::OriginalName("ICON12")] Icon12 = 13,
    [pbr::OriginalName("ICON13")] Icon13 = 14,
    [pbr::OriginalName("ICON14")] Icon14 = 15,
    [pbr::OriginalName("ICON15")] Icon15 = 16,
    [pbr::OriginalName("ICON16")] Icon16 = 17,
    [pbr::OriginalName("ICON17")] Icon17 = 18,
    [pbr::OriginalName("ICON18")] Icon18 = 19,
    [pbr::OriginalName("ICON19")] Icon19 = 20,
    [pbr::OriginalName("ICON20")] Icon20 = 21,
    [pbr::OriginalName("ICON21")] Icon21 = 22,
    [pbr::OriginalName("ICON22")] Icon22 = 23,
    [pbr::OriginalName("ICON23")] Icon23 = 24,
    [pbr::OriginalName("ICON24")] Icon24 = 25,
    [pbr::OriginalName("ICON25")] Icon25 = 26,
    [pbr::OriginalName("ICON26")] Icon26 = 27,
    [pbr::OriginalName("ICON27")] Icon27 = 28,
    [pbr::OriginalName("ICON28")] Icon28 = 29,
    [pbr::OriginalName("ICON29")] Icon29 = 30,
    [pbr::OriginalName("ICON30")] Icon30 = 31,
  }

  public enum VaultColor {
    [pbr::OriginalName("COLOR_UNSPECIFIED")] ColorUnspecified = 0,
    [pbr::OriginalName("COLOR_CUSTOM")] ColorCustom = 1,
    [pbr::OriginalName("COLOR1")] Color1 = 2,
    [pbr::OriginalName("COLOR2")] Color2 = 3,
    [pbr::OriginalName("COLOR3")] Color3 = 4,
    [pbr::OriginalName("COLOR4")] Color4 = 5,
    [pbr::OriginalName("COLOR5")] Color5 = 6,
    [pbr::OriginalName("COLOR6")] Color6 = 7,
    [pbr::OriginalName("COLOR7")] Color7 = 8,
    [pbr::OriginalName("COLOR8")] Color8 = 9,
    [pbr::OriginalName("COLOR9")] Color9 = 10,
    [pbr::OriginalName("COLOR10")] Color10 = 11,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class VaultDisplayPreferences : pb::IMessage<VaultDisplayPreferences>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VaultDisplayPreferences> _parser = new pb::MessageParser<VaultDisplayPreferences>(() => new VaultDisplayPreferences());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VaultDisplayPreferences> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PasswordManagerAccess.ProtonPass.Protobuf.VaultV1Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VaultDisplayPreferences() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VaultDisplayPreferences(VaultDisplayPreferences other) : this() {
      icon_ = other.icon_;
      color_ = other.color_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VaultDisplayPreferences Clone() {
      return new VaultDisplayPreferences(this);
    }

    /// <summary>Field number for the "icon" field.</summary>
    public const int IconFieldNumber = 1;
    private global::PasswordManagerAccess.ProtonPass.Protobuf.VaultIcon icon_ = global::PasswordManagerAccess.ProtonPass.Protobuf.VaultIcon.IconUnspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PasswordManagerAccess.ProtonPass.Protobuf.VaultIcon Icon {
      get { return icon_; }
      set {
        icon_ = value;
      }
    }

    /// <summary>Field number for the "color" field.</summary>
    public const int ColorFieldNumber = 2;
    private global::PasswordManagerAccess.ProtonPass.Protobuf.VaultColor color_ = global::PasswordManagerAccess.ProtonPass.Protobuf.VaultColor.ColorUnspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PasswordManagerAccess.ProtonPass.Protobuf.VaultColor Color {
      get { return color_; }
      set {
        color_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VaultDisplayPreferences);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VaultDisplayPreferences other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Icon != other.Icon) return false;
      if (Color != other.Color) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Icon != global::PasswordManagerAccess.ProtonPass.Protobuf.VaultIcon.IconUnspecified) hash ^= Icon.GetHashCode();
      if (Color != global::PasswordManagerAccess.ProtonPass.Protobuf.VaultColor.ColorUnspecified) hash ^= Color.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Icon != global::PasswordManagerAccess.ProtonPass.Protobuf.VaultIcon.IconUnspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Icon);
      }
      if (Color != global::PasswordManagerAccess.ProtonPass.Protobuf.VaultColor.ColorUnspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Color);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Icon != global::PasswordManagerAccess.ProtonPass.Protobuf.VaultIcon.IconUnspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Icon);
      }
      if (Color != global::PasswordManagerAccess.ProtonPass.Protobuf.VaultColor.ColorUnspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Color);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Icon != global::PasswordManagerAccess.ProtonPass.Protobuf.VaultIcon.IconUnspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Icon);
      }
      if (Color != global::PasswordManagerAccess.ProtonPass.Protobuf.VaultColor.ColorUnspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Color);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VaultDisplayPreferences other) {
      if (other == null) {
        return;
      }
      if (other.Icon != global::PasswordManagerAccess.ProtonPass.Protobuf.VaultIcon.IconUnspecified) {
        Icon = other.Icon;
      }
      if (other.Color != global::PasswordManagerAccess.ProtonPass.Protobuf.VaultColor.ColorUnspecified) {
        Color = other.Color;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Icon = (global::PasswordManagerAccess.ProtonPass.Protobuf.VaultIcon) input.ReadEnum();
            break;
          }
          case 16: {
            Color = (global::PasswordManagerAccess.ProtonPass.Protobuf.VaultColor) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Icon = (global::PasswordManagerAccess.ProtonPass.Protobuf.VaultIcon) input.ReadEnum();
            break;
          }
          case 16: {
            Color = (global::PasswordManagerAccess.ProtonPass.Protobuf.VaultColor) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Vault : pb::IMessage<Vault>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Vault> _parser = new pb::MessageParser<Vault>(() => new Vault());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Vault> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PasswordManagerAccess.ProtonPass.Protobuf.VaultV1Reflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Vault() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Vault(Vault other) : this() {
      name_ = other.name_;
      description_ = other.description_;
      display_ = other.display_ != null ? other.display_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Vault Clone() {
      return new Vault(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 2;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "display" field.</summary>
    public const int DisplayFieldNumber = 3;
    private global::PasswordManagerAccess.ProtonPass.Protobuf.VaultDisplayPreferences display_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PasswordManagerAccess.ProtonPass.Protobuf.VaultDisplayPreferences Display {
      get { return display_; }
      set {
        display_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Vault);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Vault other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Description != other.Description) return false;
      if (!object.Equals(Display, other.Display)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (display_ != null) hash ^= Display.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Description);
      }
      if (display_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Display);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Description);
      }
      if (display_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Display);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (display_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Display);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Vault other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      if (other.display_ != null) {
        if (display_ == null) {
          Display = new global::PasswordManagerAccess.ProtonPass.Protobuf.VaultDisplayPreferences();
        }
        Display.MergeFrom(other.Display);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Description = input.ReadString();
            break;
          }
          case 26: {
            if (display_ == null) {
              Display = new global::PasswordManagerAccess.ProtonPass.Protobuf.VaultDisplayPreferences();
            }
            input.ReadMessage(Display);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Description = input.ReadString();
            break;
          }
          case 26: {
            if (display_ == null) {
              Display = new global::PasswordManagerAccess.ProtonPass.Protobuf.VaultDisplayPreferences();
            }
            input.ReadMessage(Display);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
